### ISSUE TITLE
The code samples are hard to read.

### ISSUE THREAD

**Issue by mbartlett21** [onshape-public/onshape-public.github.io#1]
The code samples in the documentation are missing brackets, braces, periods, commas and semicolons unless they are highlighted"

(This is from the api keys docs)

![image](https://user-images.githubusercontent.com/29034492/100834730-24258e80-34b8-11eb-82d5-06b8311f1b3a.png)

![image](https://user-images.githubusercontent.com/29034492/100834754-2ee02380-34b8-11eb-9a04-359cb6629f3d.png)

**Comment by leilenatekle-onshape** [comment]
Changes proposed in 
`https://github.com/onshape-public/onshape-public-docs/pull/16#issue-534894024`
